/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{ts,tsx}", "./popup.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error": "#490106",
        "on-tertiary-container": "#575756",
        background: "#0e0e0e",
        "on-secondary-container": "#bfbfbf",
        "on-primary-fixed": "#3e4040",
        "tertiary-fixed-dim": "#e7e5e4",
        "secondary-fixed": "#e3e2e2",
        "on-tertiary-fixed": "#4a4949",
        "primary-dim": "#b8b9b9",
        "on-secondary-fixed-variant": "#5b5c5c",
        "surface-bright": "#2c2c2c",
        "surface-container": "#191a1a",
        "on-background": "#e7e5e4",
        secondary: "#9d9e9e",
        "on-primary-container": "#d0d0d0",
        "on-primary-fixed-variant": "#5a5c5c",
        "surface-container-high": "#1f2020",
        "tertiary-dim": "#edeaea",
        "surface-dim": "#0e0e0e",
        "secondary-fixed-dim": "#d5d4d4",
        "on-error-container": "#ff9993",
        "secondary-dim": "#9d9e9e",
        "on-surface-variant": "#acabaa",
        "error-dim": "#bb5551",
        "error-container": "#7f2927",
        "secondary-container": "#3a3c3c",
        "surface-tint": "#c6c6c7",
        "surface-container-lowest": "#000000",
        "on-surface": "#e7e5e4",
        "inverse-primary": "#5e5f60",
        error: "#ee7d77",
        "surface-variant": "#252626",
        "inverse-surface": "#fcf9f8",
        "outline-variant": "#484848",
        "primary-container": "#454747",
        outline: "#767575",
        "on-secondary": "#1f2021",
        "tertiary-fixed": "#f5f3f2",
        "primary-fixed-dim": "#d4d4d4",
        "surface-container-low": "#131313",
        "on-secondary-fixed": "#3e3f40",
        tertiary: "#fbf9f8",
        "tertiary-container": "#edeaea",
        "primary-fixed": "#e2e2e2",
        "on-tertiary-fixed-variant": "#666666",
        surface: "#0e0e0e",
        "on-tertiary": "#5f5f5f",
        "surface-container-highest": "#252626",
        "on-primary": "#3f4041",
        "inverse-on-surface": "#565555",
        primary: "#c6c6c7",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};
